import psycopg2
from database import get_db_connection

def migrate():
    conn = get_db_connection()
    try:
        with conn.cursor() as cur:
            print("Migrating schedule table...")
            # Expand column lengths
            cur.execute('ALTER TABLE schedule ALTER COLUMN name TYPE character varying(100);')
            cur.execute('ALTER TABLE schedule ALTER COLUMN detail TYPE character varying(500);')
            cur.execute('ALTER TABLE schedule ALTER COLUMN start_time TYPE character varying(10);')
            cur.execute('ALTER TABLE schedule ALTER COLUMN end_time TYPE character varying(10);')
            cur.execute('ALTER TABLE schedule ALTER COLUMN type TYPE character varying(10);')
            cur.execute('ALTER TABLE schedule ALTER COLUMN auth TYPE character varying(10);')
            # Set default for regtm
            cur.execute('ALTER TABLE schedule ALTER COLUMN regtm SET DEFAULT now();')
            # Handle idx (primary key) - make it auto-increment if it's not
            # First check if it has a sequence
            cur.execute("SELECT pg_get_serial_sequence('schedule', 'idx');")
            seq = cur.fetchone()[0]
            if not seq:
                print("Adding identity to idx...")
                cur.execute("ALTER TABLE schedule ALTER COLUMN idx ADD GENERATED BY DEFAULT AS IDENTITY;")
            
            conn.commit()
            print("Migration successful.")
    except Exception as e:
        print(f"Migration failed: {e}")
        conn.rollback()
    finally:
        conn.close()

if __name__ == "__main__":
    migrate()
